import { StyleSheet } from 'react-native';
import { CELL_SIZE, CELL_MARGIN } from 'C:/Users/Wisam/SpellCast/game_constants.js';

export const styles = StyleSheet.create({
  modernBackground: {
    flex: 1,
    backgroundColor: '#0a0a0f',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  startContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  titleContainer: {
    position: 'relative',
    marginBottom: 40,
  },
  modernTitle: {
    fontSize: 56,
    fontWeight: '900',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 3,
    textShadowColor: 'rgba(102, 126, 234, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  titleGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    fontSize: 56,
    fontWeight: '900',
    color: '#667eea',
    textAlign: 'center',
    letterSpacing: 3,
    opacity: 0.3,
    textShadowColor: '#667eea',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 30,
  },
  startSubtitle: {
    fontSize: 22,
    color: '#b8c5ff',
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: '600',
  },
  startDescription: {
    fontSize: 16,
    color: '#8b9dc3',
    marginBottom: 50,
    textAlign: 'center',
    lineHeight: 24,
  },
  modernStartButton: {
    backgroundColor: 'rgba(102, 126, 234, 0.9)',
    paddingVertical: 18,
    paddingHorizontal: 50,
    borderRadius: 30,
    marginBottom: 20,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 8,
  },
  startButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 20,
    letterSpacing: 1,
  },
  modernBackButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  backButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
  },
  gameContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 60,
  },
  modernHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '95%',
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  headerLeft: {
    flex: 1,
  },
  modernGameTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  timerContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  modernTimer: {
    fontSize: 24,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: 1,
  },
  timerCritical: {
    color: '#ff4757',
    textShadowColor: '#ff4757',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  scoreContainer: {
    alignItems: 'center',
  },
  modernScore: {
    fontSize: 18,
    fontWeight: '700',
    color: '#667eea',
    letterSpacing: 1,
  },
  scoreLabel: {
    fontSize: 10,
    color: '#8b9dc3',
    fontWeight: '600',
    letterSpacing: 2,
  },
  modernPauseButton: {
    flex: 1,
    alignItems: 'flex-end',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  pauseIcon: {
    fontSize: 18,
  },
  modernGrid: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    padding: 15,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  gridRow: {
    flexDirection: 'row',
  },
  modernCell: {
    width: CELL_SIZE,
    height: CELL_SIZE,
    margin: CELL_MARGIN,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 15,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    position: 'relative',
  },
  selectedCell: {
    backgroundColor: '#667eea',
    shadowColor: '#667eea',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 8,
  },
  modernLetter: {
    fontSize: 28,
    fontWeight: '900',
    color: '#2c3e50',
    letterSpacing: 1,
  },
  selectedLetter: {
    color: '#ffffff',
    textShadowColor: 'rgba(255, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  cellGlow: {
    position: 'absolute',
    top: -5,
    left: -5,
    right: -5,
    bottom: -5,
    backgroundColor: '#667eea',
    borderRadius: 20,
    opacity: 0.3,
    zIndex: -1,
  },
  modernTrailPoint: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#667eea',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
  },
  currentWordContainer: {
    position: 'absolute',
    bottom: 180,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.5)',
  },
  currentWordLabel: {
    color: '#8b9dc3',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 5,
  },
  currentWord: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 3,
    minHeight: 30,
  },
  wordsPanel: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.3)',
    maxHeight: 140,
  },
  wordsPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  wordsPanelTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
  },
  wordCount: {
    color: '#667eea',
    fontSize: 18,
    fontWeight: '800',
    backgroundColor: 'rgba(102, 126, 234, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  wordsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  wordChip: {
    backgroundColor: 'rgba(102, 126, 234, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.4)',
  },
  wordText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginRight: 8,
  },
  wordScore: {
    color: '#667eea',
    fontSize: 12,
    fontWeight: '700',
  },
  // Menu and Instructions styles
  menuContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#0a0a0f',
  },
  menuTitle: {
    fontSize: 48,
    fontWeight: '900',
    color: '#ffffff',
    marginBottom: 40,
    letterSpacing: 3,
    textShadowColor: '#667eea',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  menuButton: {
    backgroundColor: 'rgba(102, 126, 234, 0.2)',
    padding: 18,
    borderRadius: 25,
    marginVertical: 10,
    width: '80%',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(102, 126, 234, 0.4)',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
  },
  instructionsContainer: {
    flex: 1,
    justifyContent: 'center',
    padding: 30,
    backgroundColor: '#0a0a0f',
  },
  instructionsText: {
    color: 'white',
    fontSize: 18,
    lineHeight: 32,
    marginVertical: 30,
    textAlign: 'left',
  },
  
// New styles to add after the existing cellGlow style:
multiplierCell: {
  backgroundColor: '#ff6b6b',
  borderWidth: 3,
  borderColor: '#ffdd59',
  shadowColor: '#ffdd59',
  shadowOpacity: 0.8,
  shadowRadius: 20,
  elevation: 12,
},
multiplierLetter: {
  color: '#ffffff',
  textShadowColor: '#ffdd59',
  textShadowOffset: { width: 0, height: 0 },
  textShadowRadius: 12,
},
multiplierGlow: {
  position: 'absolute',
  top: -10,
  left: -10,
  right: -10,
  bottom: -10,
  backgroundColor: '#ffdd59',
  borderRadius: 28,
  opacity: 0.6,
  zIndex: -1,
},
multiplierBadge: {
  position: 'absolute',
  top: -5,
  right: -5,
  backgroundColor: '#ff4757',
  borderRadius: 10,
  paddingHorizontal: 6,
  paddingVertical: 2,
  borderWidth: 1,
  borderColor: '#ffffff',
},
multiplierText: {
  color: '#ffffff',
  fontSize: 10,
  fontWeight: '900',
  letterSpacing: 0.5,
},
multiplierIndicator: {
  color: '#ffdd59',
  fontSize: 14,
  fontWeight: '800',
  textAlign: 'center',
  marginTop: 5,
  textShadowColor: '#ffdd59',
  textShadowOffset: { width: 0, height: 0 },
  textShadowRadius: 8,
},
});
