/**
 * Every sound file, in one place.
 *
 * Generated by tools/generate_audio.js. Drop a replacement with the same name
 * into assets/audio/ and nothing else needs to change.
 */

export const SELECT_LADDER = [
  require('../../assets/audio/select_0.wav'),
  require('../../assets/audio/select_1.wav'),
  require('../../assets/audio/select_2.wav'),
  require('../../assets/audio/select_3.wav'),
  require('../../assets/audio/select_4.wav'),
  require('../../assets/audio/select_5.wav'),
];

export const SOUNDS = {
  word: require('../../assets/audio/word.wav'),
  invalid: require('../../assets/audio/invalid.wav'),
  combo: require('../../assets/audio/combo.wav'),
  tick: require('../../assets/audio/tick.wav'),
  gameover: require('../../assets/audio/gameover.wav'),
  shuffle: require('../../assets/audio/shuffle.wav'),
  start: require('../../assets/audio/start.wav'),
};

/**
 * Every music track, keyed. Names, prices and blurbs live in tracks.js, which
 * is pure data and therefore testable; Metro needs literal paths here.
 *
 * music.wav keeps its original filename so the promise above still holds for
 * the default track.
 */
export const MUSIC = {
  drift: require('../../assets/audio/music.wav'),
  pulse: require('../../assets/audio/pulse.wav'),
  lantern: require('../../assets/audio/lantern.wav'),
  fathom: require('../../assets/audio/fathom.wav'),
};
