/**
 * Every sound file, in one place.
 *
 * Effects are generated by tools/generate_audio.js; drop a replacement with the
 * same name into assets/audio/ and nothing else needs to change. Music is CC0
 * tracks from OpenGameArt - see tracks.js for who made each one.
 */

export const SELECT_LADDER = [
  require('../../assets/audio/select_0.wav'),
  require('../../assets/audio/select_1.wav'),
  require('../../assets/audio/select_2.wav'),
  require('../../assets/audio/select_3.wav'),
  require('../../assets/audio/select_4.wav'),
  require('../../assets/audio/select_5.wav'),
];

export const SOUNDS = {
  word: require('../../assets/audio/word.wav'),
  invalid: require('../../assets/audio/invalid.wav'),
  combo: require('../../assets/audio/combo.wav'),
  tick: require('../../assets/audio/tick.wav'),
  gameover: require('../../assets/audio/gameover.wav'),
  shuffle: require('../../assets/audio/shuffle.wav'),
  start: require('../../assets/audio/start.wav'),
};

/**
 * Every music track, keyed. Names, prices and credits live in tracks.js, which
 * is pure data and therefore testable; Metro needs literal paths here.
 *
 * CC0 tracks from OpenGameArt, as AAC in M4A rather than MP3, to avoid the
 * short gap MP3 leaves at a loop point. The keys predate the music (see tracks.js) so purchases carry over.
 */
export const MUSIC = {
  drift: require('../../assets/audio/music/outer-space.m4a'),
  pulse: require('../../assets/audio/music/vintage-menu.m4a'),
  lantern: require('../../assets/audio/music/lofi-loop.m4a'),
  grove: require('../../assets/audio/music/cathedral-forest.m4a'),
  fathom: require('../../assets/audio/music/underwater-theme-ii.m4a'),
};
