'use strict';
/**
 * Regenerates the two word lists the game ships.
 *
 *   node tools/build_dictionary.js
 *
 * Two tiers, on purpose:
 *
 *   words.enable.js  ENABLE1, the public-domain word-game lexicon (Alan Beale,
 *                    released to the public domain). Used to VALIDATE what the
 *                    player traced, so a real word is never rejected.
 *   words.common.js  The common-word subset. Used for par, board quality and
 *                    seed words, so those numbers reflect words people actually
 *                    know rather than obscure ones no human will ever find.
 *
 * The previous list was a web-frequency dump: it accepted AMD, ASN, ATM and
 * AARON while rejecting ordinary words like CAT.
 *
 * Sources are downloaded on first run into tools/sources/ (gitignored).
 */
const fs = require('fs');
const https = require('https');
const path = require('path');

const SOURCES = {
  'enable1.txt': 'https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt',
  'popular.txt': 'https://raw.githubusercontent.com/dolph/dictionary/master/popular.txt',
};

const MIN_LENGTH = 3;
/** A 5x5 board can technically trace more, but 9 keeps the trie affordable and
 *  the same cap applies to validation and solving, so the two can never disagree. */
const MAX_LENGTH = 9;

const sourceDir = path.join(__dirname, 'sources');
const assetDir = path.join(__dirname, '..', 'assets');

const download = (url, destination) =>
  new Promise((resolve, reject) => {
    const request = (target, redirects = 0) => {
      https
        .get(target, (response) => {
          if (response.statusCode >= 300 && response.statusCode < 400 && response.headers.location) {
            if (redirects > 5) return reject(new Error('too many redirects'));
            return request(response.headers.location, redirects + 1);
          }
          if (response.statusCode !== 200) {
            return reject(new Error(`${target} responded ${response.statusCode}`));
          }
          const file = fs.createWriteStream(destination);
          response.pipe(file);
          file.on('finish', () => file.close(resolve));
        })
        .on('error', reject);
    };
    request(url);
  });

const readList = (file) =>
  fs
    .readFileSync(file, 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim().toUpperCase())
    .filter((word) => word.length >= MIN_LENGTH && word.length <= MAX_LENGTH && /^[A-Z]+$/.test(word));

const writeModule = (file, name, words, note) => {
  const header =
    `/* GENERATED by tools/build_dictionary.js - do not edit by hand.\n` +
    ` * ${note}\n` +
    ` * ${words.length} words, ${MIN_LENGTH}-${MAX_LENGTH} letters, space separated.\n` +
    ` * One string literal rather than an array: 1 allocation instead of ${words.length}.\n` +
    ` */\n`;
  fs.writeFileSync(file, `${header}export default '${words.join(' ')}';\n`);
  const kb = (fs.statSync(file).size / 1024).toFixed(0);
  console.log(`${name.padEnd(16)} ${String(words.length).padStart(7)} words  ${kb} KB`);
};

const main = async () => {
  fs.mkdirSync(sourceDir, { recursive: true });

  for (const [file, url] of Object.entries(SOURCES)) {
    const destination = path.join(sourceDir, file);
    if (fs.existsSync(destination)) continue;
    console.log(`downloading ${file} ...`);
    await download(url, destination);
  }

  const enable = readList(path.join(sourceDir, 'enable1.txt'));
  const popularRaw = readList(path.join(sourceDir, 'popular.txt'));

  const enableSet = new Set(enable);
  const common = popularRaw.filter((word) => enableSet.has(word));

  const sorted = [...new Set(enable)].sort();
  const commonSorted = [...new Set(common)].sort();

  writeModule(
    path.join(assetDir, 'words.enable.js'),
    'words.enable',
    sorted,
    'ENABLE1 (public domain) - the validation tier.',
  );
  writeModule(
    path.join(assetDir, 'words.common.js'),
    'words.common',
    commonSorted,
    'Common subset of ENABLE1 - the par / quality / seed tier.',
  );

  const byLength = {};
  commonSorted.forEach((word) => {
    byLength[word.length] = (byLength[word.length] || 0) + 1;
  });
  console.log('common words by length:', JSON.stringify(byLength));
};

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
